// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoRl57pRp72oo4X3XDoK8j7OFHiJ7qTYM',
    appId: '1:572207067835:web:d4a4b4af808166758eef9e',
    messagingSenderId: '572207067835',
    projectId: 'rider-a93d3',
    authDomain: 'rider-a93d3.firebaseapp.com',
    storageBucket: 'rider-a93d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgnYlnSwRhXs3hYF5eHgoClB8MgQv1neI',
    appId: '1:572207067835:android:e1722ae692b651a38eef9e',
    messagingSenderId: '572207067835',
    projectId: 'rider-a93d3',
    storageBucket: 'rider-a93d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf7P3ZnjHw-eR-CXW0Tsa_m1tnn6HJkP4',
    appId: '1:572207067835:ios:fbb189245995d8fa8eef9e',
    messagingSenderId: '572207067835',
    projectId: 'rider-a93d3',
    storageBucket: 'rider-a93d3.firebasestorage.app',
    iosBundleId: 'com.example.rider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoRl57pRp72oo4X3XDoK8j7OFHiJ7qTYM',
    appId: '1:572207067835:web:1ccda98d93a8a6c58eef9e',
    messagingSenderId: '572207067835',
    projectId: 'rider-a93d3',
    authDomain: 'rider-a93d3.firebaseapp.com',
    storageBucket: 'rider-a93d3.firebasestorage.app',
  );
}
